### PR TITLE
Added X5/3 specific changes to X5/3 branch (adding samples and HOTTag…

### PR DESCRIPTION
**Pull request by farrah-simpson**
…gingEfficiencies implementation

### CODE REVIEW

**Comment by emanueleusai** [comment]
Hi Farrah,

Does this commit contain anything relevant to the 4tops analysis?

If not, this should go into a separate repository for the X5/3 analysis (I can create one for you!).

Alternatively, if you really want to keep the X5/3 analysis in our repo (e.g. to be able to merge more easily developments in 4tops) we should put it in a separate branch. I see you correctly created a new branch in your local repo, but you're still making a PR to the master branch of the original repo. I think I have to create a new branch and then you have to create a new PR to that new branch.

Let me know how you'd like to proceed.

Emanuele

**Comment by farrah-simpson** [comment]
Hi Emanuele,

Yes I wanted to make it easier to merge developments in the 4tops branch with mine. However, there is a bug in the current step1 that Sinan is fixing so once he pushes his changes I will update my branch and then we can proceed by making a new branch for X5/3 and I can create a new PR to that new branch. Thanks!

**Comment by sisagir** [comment]
Hi, I just pushed my updates to the repository. But to be clear, these are not bugs, they are just some fixes. Also @farrah-simpson please do not add binary files to the repository.

**Comment by emanueleusai** [comment]
Hi Farrah,

I changed the base of your PR to a new branch named X5/3 which is (as of now) an exact copy of the main branch.
Please merge Sinan's changes and remove the binary files. After these changes we're ready to merge!
Note you can just add commits to your local X5/3 branch and they will be added to this PR. 
To avoid committing unneeded files in the future you can edit the file ".gitignore" and add the extensions you want excluded, e.g.:
*.d
*.so
*.pcm

**Pull request merged**
